# Generated by Django 5.1.7 on 2025-03-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_academicyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyear_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_examtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtype_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_notification', models.CharField(max_length=50)),
                ('notification_limit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_alumnireg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnireg_name', models.CharField(max_length=50)),
                ('alumnireg_email', models.CharField(max_length=50)),
                ('alumnireg_contact', models.CharField(max_length=50)),
                ('alumnireg_dob', models.DateField(null=True)),
                ('alumnireg_password', models.CharField(max_length=50)),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_name', models.CharField(max_length=50)),
                ('examination_mark', models.CharField(max_length=50)),
                ('examination_qno', models.CharField(max_length=50)),
                ('examination_time', models.CharField(max_length=50)),
                ('examination_status', models.IntegerField(default=0)),
                ('time', models.TimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('examtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_examtype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_name', models.CharField(max_length=50)),
                ('hod_email', models.CharField(max_length=50)),
                ('hod_contact', models.CharField(max_length=50)),
                ('hod_dob', models.DateField(null=True)),
                ('hod_password', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost_details', models.CharField(max_length=50)),
                ('jobpost_companyname', models.CharField(max_length=50)),
                ('jobpost_mincgpa', models.CharField(max_length=50)),
                ('jobpost_backlog', models.CharField(max_length=50)),
                ('jobpost_file_doc', models.CharField(max_length=50)),
                ('jobpost_lastdate', models.DateField()),
                ('jobpost_status', models.IntegerField(default=0)),
                ('alumini', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_alumnireg')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_examination')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_questions')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_studentreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentreg_photo', models.FileField(null=True, upload_to='Assets/User/')),
                ('studentreg_ktuid', models.CharField(max_length=50)),
                ('studentreg_name', models.CharField(max_length=50)),
                ('studentreg_email', models.CharField(max_length=50)),
                ('studentreg_contact', models.CharField(max_length=50)),
                ('studentreg_cgpa', models.CharField(max_length=50)),
                ('studentreg_backlog', models.CharField(max_length=50)),
                ('studentreg_dob', models.DateField(null=True)),
                ('studentreg_password', models.CharField(max_length=50)),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_semester')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_content', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_studentreg')),
            ],
        ),
    ]
