# Generated by Django 5.1.6 on 2025-03-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_examination',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department'),
            preserve_default=False,
        ),
    ]
