# Generated by Django 5.1.6 on 2025-03-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_tbl_examination_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_examination',
            name='examination_date',
            field=models.DateField(null=True),
        ),
    ]
