# Generated by Django 5.1.6 on 2025-04-01 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_tbl_examination_examination_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_jobpost',
            name='department',
        ),
        migrations.CreateModel(
            name='tbl_jobpostdepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_department')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_jobpost')),
            ],
        ),
    ]
