# Generated by Django 5.1.6 on 2025-04-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_remove_tbl_jobpost_department_tbl_jobpostdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_jobpost',
            name='jobpost_file_doc',
            field=models.FileField(upload_to='Assets/jobpost/'),
        ),
    ]
