# Generated by Django 5.1.7 on 2025-03-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('examinationbody_status', models.IntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_studentreg')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_examinationanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationanswers_statusq', models.IntegerField(default=0)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='Administrator.tbl_options')),
                ('myanswer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myanswer', to='Administrator.tbl_options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_questions')),
                ('examinationbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_examinationbody')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_jobrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_jobpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_studentreg')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_timmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timmer', models.TimeField()),
                ('timmer_status', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_examination')),
            ],
        ),
    ]
